# Generated by Django 6.0.4 on 2026-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('course', models.CharField(choices=[('A', 'A 創意繪畫 1.5h'), ('B', 'B 創意繪畫 2h'), ('C', 'C 繪本創作 2h'), ('D', 'D 連環漫畫 2h'), ('E', 'E 插畫 2h'), ('F', 'F 基礎素描 2h'), ('G', 'G 基礎水彩 2h')], max_length=1)),
                ('day', models.CharField(choices=[('mon', '週一'), ('tue', '週二'), ('wed', '週三'), ('thu', '週四'), ('fri', '週五'), ('sat', '週六'), ('sun', '週日')], max_length=3)),
                ('time_slot', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
