# Generated by Django 6.0.4 on 2026-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('mon', '週一班'), ('tue', '週二班'), ('wed', '週三班'), ('thu', '週四班'), ('fri', '週五班'), ('sat', '週六班'), ('sun', '週日班')], default='thu', max_length=3),
        ),
    ]
