# Generated by Django 6.0.4 on 2026-05-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_date', models.DateField()),
                ('class_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '待排課'), ('waiting', '等家長回覆'), ('scheduled', '已排定'), ('done', '補課完成')], default='pending', max_length=10)),
                ('makeup_date', models.DateField(blank=True, null=True)),
                ('makeup_time', models.TimeField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
