# Generated by Django 6.0.4 on 2026-05-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_makeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('sent_date', models.DateField()),
                ('original_amount', models.IntegerField(default=3600)),
                ('discount', models.BooleanField(default=False)),
                ('final_amount', models.IntegerField(default=3600)),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
